version: '3'

services:
  xmpp_server:
    extends:
      file: './packages/xmpp_server/docker-compose.yml'
      service: xmpp_server

  agent:
    depends_on:
      - xmpp_server
    extends:
      file: './packages/agents/docker-compose.yml'
      service: agents
    environment:
      AGENT_NAME: 'agent'
      AGENT_PASSWORD: 'agent'
      XMPP: 'xmpp_server'
      NOTIFY_ADDR: '0.0.0.0'
      NOTIFY_PORT: 8080
    scale: 3
    ports:
      - '5000-5002:8080'
